name: multi_media_picker_example
description: Demonstrates how to use the multi_media_picker plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  multi_media_picker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter