name: multi_media_picker
description: A fork of the official image_picker plugin that adds the functionality to pick multiple images.
version: 0.2.4
homepage: https://github.com/ja2375/multi_media_picker

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  video_player: ">=0.10.11+2 <0.11.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.javih.multimediapicker
        pluginClass: MultiMediaPickerPlugin
      ios:
        pluginClass: MultiMediaPickerPlugin
